EPOCHS = 5
LR = 1e-5
save = True
name_saving = "final_predictions.csv"
name_file = "labelled articles cleaned.csv"
increase_data = False
batch_size = 4
text_column = "text"
test_column = "text"
size_training = 50_000
column_labels = "naf"
max_length = 512
use_samplers = True
